export class BeanControldeproduccion{
      codigo?:string;
	  llave?:number;
	  fechacreacion?:string;
	  horacreacion?:string;
	  nombre?:string;
	  placa?:string;
	  vin?:string;
	  kilometraje?:string;
	  asesor?:string;
	  estado?:string;
	  carro?:string;
	  codcliente?: number; 
	  total?: number;
	  colores?:string;
	  anio?:string;
	  observacion?:string;
	  segurosiniestro?: number;
	  clientesiniestro?:string;
	  codsucursal?: number;
	  codreclamo?:string;
	  placahistorial?:string;
	  valorizada?:string;
	  garantia?:string;
	   codasesor?: number;
	  desmarca?:string;
	  doccliente?:string;
	  tipoestadoos?:string;
	  inicialesmarca?:string;
	  estope?:string;
	  desestope?:string;
	  dtelavadoprevioinicio?:Date;
	  dtelavadopreviofin?:Date;
	  dtecontrolcalidadinicio?:Date;
	  dtecontrolcalidadfin?:Date;
	  dtelavadopreentregainicio?:Date;
	  dtelavadopreentregafin?:Date;
	  nrobuffer?:string;

}